name: camelgym
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - faiss-cpu=1.8.0
  - libcxx=16.0.6
  - libfaiss=1.8.0
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libsqlite=3.45.2
  - libzlib=1.2.13
  - llvm-openmp=18.1.2
  - ncurses=6.4
  - nomkl=3.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.21
  - openblas-devel=0.3.21
  - openssl=3.2.1
  - packaging=23.2
  - pip=23.3.1
  - pydantic=2.6.4
  - pydantic-core=2.16.3
  - python=3.10.9
  - python_abi=3.10
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - typing_extensions=4.9.0
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - anyio==4.3.0
      - asgiref==3.8.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - backoff==2.2.1
      - bcrypt==4.1.2
      - build==1.2.1
      - cachetools==5.3.3
      - camel-ai==0.1.1
      - camelgym==0.0.0
      - charset-normalizer==3.3.2
      - chroma-hnswlib==0.7.3
      - chromadb==0.4.24
      - click==8.1.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - dataclasses-json==0.6.4
      - deprecated==1.2.14
      - distro==1.9.0
      - exceptiongroup==1.2.0
      - fastapi==0.110.1
      - filelock==3.13.3
      - fire==0.6.0
      - flatbuffers==24.3.25
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitignore-parser==0.1.11
      - gitpython==3.1.43
      - google-auth==2.29.0
      - googleapis-common-protos==1.63.0
      - grpcio==1.62.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - humanfriendly==10.0
      - idna==3.6
      - imap-tools==1.6.0
      - importlib-metadata==7.0.0
      - importlib-resources==6.4.0
      - joblib==1.3.2
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kubernetes==29.0.0
      - langchain==0.1.14
      - langchain-community==0.0.31
      - langchain-core==0.1.40
      - langchain-text-splitters==0.0.1
      - langsmith==0.1.40
      - loguru==0.7.2
      - markdown-it-py==3.0.0
      - marshmallow==3.21.1
      - mdurl==0.1.2
      - mmh3==4.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - oauthlib==3.2.2
      - onnxruntime==1.17.1
      - openai==1.16.1
      - opentelemetry-api==1.24.0
      - opentelemetry-exporter-otlp-proto-common==1.24.0
      - opentelemetry-exporter-otlp-proto-grpc==1.24.0
      - opentelemetry-instrumentation==0.45b0
      - opentelemetry-instrumentation-asgi==0.45b0
      - opentelemetry-instrumentation-fastapi==0.45b0
      - opentelemetry-proto==1.24.0
      - opentelemetry-sdk==1.24.0
      - opentelemetry-semantic-conventions==0.45b0
      - opentelemetry-util-http==0.45b0
      - orjson==3.10.0
      - overrides==7.7.0
      - pandas==2.2.1
      - pillow==10.3.0
      - posthog==3.5.0
      - protobuf==4.25.3
      - pulsar-client==3.4.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygments==2.17.2
      - pypika==0.48.9
      - pyproject-hooks==1.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.34.0
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rpds-py==0.18.0
      - rsa==4.9
      - scikit-learn==1.4.1.post1
      - scipy==1.13.0
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.29
      - starlette==0.37.2
      - sympy==1.12
      - tenacity==8.2.3
      - termcolor==2.4.0
      - threadpoolctl==3.4.0
      - tiktoken==0.6.0
      - tokenizers==0.15.2
      - tomli==2.0.1
      - tqdm==4.66.2
      - typer==0.12.0
      - typer-cli==0.12.0
      - typer-slim==0.12.0
      - typing-extensions==4.10.0
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - watchfiles==0.21.0
      - websocket-client==1.7.0
      - websockets==12.0
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.18.1
